# Application Properties
spring.application.name=course-service

## Datasource Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/coursedb
#spring.datasource.username=user
#spring.datasource.password=password
#
## JPA/Hibernate Properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Server Configuration
server.port=9092

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Application Info
info.app.name=course-service
info.app.description=This is course service from config server[Rabbit MQ-Bus refresh]
info.app.version=1.0
